#1. Import the NUMPY package under the name np.

In [1]:
import numpy as np

#2. Print the NUMPY version and the configuration.

In [3]:
print(np.__version__)

1.18.5


#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
#Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [5]:
a = np.random.rand(2,3,5)

#Print a.

In [6]:
a

array([[[0.37240623, 0.16285182, 0.75051794, 0.84710375, 0.67396568],
        [0.94271565, 0.87316004, 0.84843808, 0.68212606, 0.64645637],
        [0.96101702, 0.78553598, 0.37980481, 0.13092673, 0.99346276]],

       [[0.98126698, 0.98298606, 0.79958896, 0.16306496, 0.4622687 ],
        [0.00507773, 0.42858791, 0.50598607, 0.8258779 , 0.19553284],
        [0.28950028, 0.89989244, 0.43126619, 0.24713274, 0.2175906 ]]])

#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

In [13]:
b = np.ones((5,2,3),dtype = int)

#6. Print b.

In [14]:
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#7. Do a and b have the same size? How do you prove that in Python code?

In [16]:
a.size == b.size

True

#8. Are you able to add a and b? Why or why not?

In [19]:
a + b

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

No puedo sumar los arrays porque por mucho que tengan el mismo tamaño (mismo número de elementos), la estructura que tienen es distinta, es decir, que el número de filas y columnas no es el mismo (no sé como llamar al tercer rango). Esto impide sumar los arrays, porque no puedes sumar 2 filas de 'a' a 5 de 'b' ya que tres filas de 'b' se quedarían sin sumar. Lo mismo sucedería con en el resto de los parámetros. 

#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

In [41]:
c = b.transpose()

In [42]:
print(c)

[[[1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]]]


In [295]:
c.shape

(3, 2, 5)

#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

In [306]:
a = a.reshape(3,2,5)

In [302]:
print(a)

[[[0.37240623 0.16285182 0.75051794 0.84710375 0.67396568]
  [0.94271565 0.87316004 0.84843808 0.68212606 0.64645637]]

 [[0.96101702 0.78553598 0.37980481 0.13092673 0.99346276]
  [0.98126698 0.98298606 0.79958896 0.16306496 0.4622687 ]]

 [[0.00507773 0.42858791 0.50598607 0.8258779  0.19553284]
  [0.28950028 0.89989244 0.43126619 0.24713274 0.2175906 ]]]


In [290]:
d = a + c

In [291]:
d.shape

(3, 2, 5)

#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

In [305]:
print(a)

[[[0.37240623 0.16285182 0.75051794 0.84710375 0.67396568]
  [0.94271565 0.87316004 0.84843808 0.68212606 0.64645637]
  [0.96101702 0.78553598 0.37980481 0.13092673 0.99346276]]

 [[0.98126698 0.98298606 0.79958896 0.16306496 0.4622687 ]
  [0.00507773 0.42858791 0.50598607 0.8258779  0.19553284]
  [0.28950028 0.89989244 0.43126619 0.24713274 0.2175906 ]]]


In [299]:
print(d)

[[[1.37240623 1.16285182 1.75051794 1.84710375 1.67396568]
  [1.94271565 1.87316004 1.84843808 1.68212606 1.64645637]]

 [[1.96101702 1.78553598 1.37980481 1.13092673 1.99346276]
  [1.98126698 1.98298606 1.79958896 1.16306496 1.4622687 ]]

 [[1.00507773 1.42858791 1.50598607 1.8258779  1.19553284]
  [1.28950028 1.89989244 1.43126619 1.24713274 1.2175906 ]]]


La principal diferencia es que se ha sumado 1 a todos los elementos de a. Ahora que tienen misma dimensión y misma estructura es posible hacer operaciones con los arrays, lo contrario a lo que pasaba con a y c

#12. Multiply a and c. Assign the result to e.

In [307]:
e = a*c

#13. Does e equal to a? Why or why not?

In [52]:
print(e)

[[[0.37240623 0.16285182 0.75051794 0.84710375 0.67396568]
  [0.94271565 0.87316004 0.84843808 0.68212606 0.64645637]]

 [[0.96101702 0.78553598 0.37980481 0.13092673 0.99346276]
  [0.98126698 0.98298606 0.79958896 0.16306496 0.4622687 ]]

 [[0.00507773 0.42858791 0.50598607 0.8258779  0.19553284]
  [0.28950028 0.89989244 0.43126619 0.24713274 0.2175906 ]]]


'e' es igual a 'a' porque cada 1 en 'c' está multiplicando su respectivo elemento en 'a', de tal forma que el resultado es una matriz con los mismos elementos que la original

#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

In [53]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

In [164]:
print(d_max)
print(d_min)
print(d_mean)

1.9934627593432064
1.0050777276826124
1.5828703097373176


#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

In [312]:
f = np.empty((2,3,5),dtype= int)

#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.

In [105]:
r = [z for x in d for y in x for z in y ]

In [82]:
s = [z for x in f for y in x for z in y]

In [315]:
r = []

for column in d:
    for row in column:
        for i in row: 
            if  d_min<i<d_mean:
                i = 25
            elif d_mean<i< d_max:
                i = 75
            elif i == d_min:
                i = 0
            elif i == d_mean:
                i = 50
            elif i == d_max:
                i = 100
            np.array(r.append(i))
            

In [316]:
r = np.array(r)

In [317]:
f = r.reshape(2,3,5)

In [284]:
print(d)

[[[1.37240623 1.16285182 1.75051794 1.84710375 1.67396568]
  [1.94271565 1.87316004 1.84843808 1.68212606 1.64645637]
  [1.96101702 1.78553598 1.37980481 1.13092673 1.99346276]]

 [[1.98126698 1.98298606 1.79958896 1.16306496 1.4622687 ]
  [1.00507773 1.42858791 1.50598607 1.8258779  1.19553284]
  [1.28950028 1.89989244 1.43126619 1.24713274 1.2175906 ]]]


In [318]:
print(f)

[[[ 25  25  75  75  75]
  [ 75  75  75  75  75]
  [ 75  75  25  25 100]]

 [[ 75  75  75  25  25]
  [  0  25  25  75  25]
  [ 25  75  25  25  25]]]


#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:

In [286]:
k = []

for column in d:
    for row in column:
        for i in row: 
            if  d_min<i<d_mean:
                i = "A"
            elif d_mean<i< d_max:
                i = "B"
            elif i == d_min:
                i = "C"
            elif i == d_mean:
                i = "D"
            elif i == d_max:
                i = "E"
            np.array(k.append(i))

In [287]:
l = np.array(k)

In [288]:
w = l.reshape(2,3,5)

In [289]:
print(w)

[[['A' 'A' 'B' 'B' 'B']
  ['B' 'B' 'B' 'B' 'B']
  ['B' 'B' 'A' 'A' 'E']]

 [['B' 'B' 'B' 'A' 'A']
  ['C' 'A' 'A' 'B' 'A']
  ['A' 'B' 'A' 'A' 'A']]]
