In [4]:
import numpy as np
a = np.random.rand(2,3,5)

In [6]:
print(a)

[[[0.97408506 0.06500717 0.37771411 0.4678553  0.42922865]
  [0.76653658 0.99421644 0.0909749  0.51827688 0.46981964]
  [0.15782261 0.16014089 0.13599348 0.18436508 0.87384691]]

 [[0.97531524 0.72183467 0.66124983 0.51486556 0.77791525]
  [0.60188954 0.37019651 0.59751397 0.56205001 0.02342677]
  [0.81474126 0.51206676 0.3777501  0.99016849 0.60816267]]]


In [7]:
b = np.ones((5,2,3))

In [8]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [11]:
comparison = a == b
equal_arrays = comparison.all()
print(equal_arrays)

<ipython-input-11-554e97fc9720>:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  comparison = a == b


AttributeError: 'bool' object has no attribute 'all'

In [14]:
print('greater_equal(a, b) = ', np.greater_equal(a,b))

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [69]:
print(a.size)
print (b.size)
if a.size[0] != b.size[0]:
    print('different size')
else: print('same size')

30
30


TypeError: 'int' object is not subscriptable

In [22]:
comparison = a_shape == b_shape
equal_arrays = comparison.all()
print(equal_arrays)

AttributeError: 'bool' object has no attribute 'all'

In [26]:
a + b

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [56]:
c = b.T
print(c)
c.shape

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


(3, 2, 5)

In [73]:
c = np.transpose(b, (1,2,0))
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [72]:
d = np.add(a,c)

In [74]:
print('hello')

hello


In [75]:
print(a)
print(b)

[[[0.97408506 0.06500717 0.37771411 0.4678553  0.42922865]
  [0.76653658 0.99421644 0.0909749  0.51827688 0.46981964]
  [0.15782261 0.16014089 0.13599348 0.18436508 0.87384691]]

 [[0.97531524 0.72183467 0.66124983 0.51486556 0.77791525]
  [0.60188954 0.37019651 0.59751397 0.56205001 0.02342677]
  [0.81474126 0.51206676 0.3777501  0.99016849 0.60816267]]]
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [76]:
e = np.multiply(a,c)

In [77]:
print(e)

[[[0.97408506 0.06500717 0.37771411 0.4678553  0.42922865]
  [0.76653658 0.99421644 0.0909749  0.51827688 0.46981964]
  [0.15782261 0.16014089 0.13599348 0.18436508 0.87384691]]

 [[0.97531524 0.72183467 0.66124983 0.51486556 0.77791525]
  [0.60188954 0.37019651 0.59751397 0.56205001 0.02342677]
  [0.81474126 0.51206676 0.3777501  0.99016849 0.60816267]]]


In [83]:
d_min = np.amin(d)
d_max = np.amax(d)
d_mean = np.mean(d)
print(d_min)
print(d_max)
print(d_mean)

1.023426774900885
1.9942164430359808
1.5258343441508968


In [84]:
f = np.empty((2,3,5))

In [85]:
print(f)

[[[0.97408506 0.06500717 0.37771411 0.4678553  0.42922865]
  [0.76653658 0.99421644 0.0909749  0.51827688 0.46981964]
  [0.15782261 0.16014089 0.13599348 0.18436508 0.87384691]]

 [[0.97531524 0.72183467 0.66124983 0.51486556 0.77791525]
  [0.60188954 0.37019651 0.59751397 0.56205001 0.02342677]
  [0.81474126 0.51206676 0.3777501  0.99016849 0.60816267]]]


In [86]:
f = 25 * (d > d_min) * (d < d_mean) + 75 * (d < d_max) * (d > d_mean) + 0 * (d == d_min) + 100 * (d == d_max)

In [87]:
print(f)

[[[ 75  25  25  25  25]
  [ 75 100  25  25  25]
  [ 25  25  25  25  75]]

 [[ 75  75  75  25  75]
  [ 75  25  75  75   0]
  [ 75  25  25  75  75]]]


In [95]:
from string import ascii_uppercase
d = dict(enumerate(ascii_uppercase))
map = np.f(array(string.ascii_uppercase))
data = data.astype(int)

AttributeError: module 'numpy' has no attribute 'f'

In [96]:
f_mapping = ['A' if i==0 elif 'B' i==25 elif 'C' if i==75 else 'D' for i in f]

SyntaxError: invalid syntax (<ipython-input-96-9ae309814eed>, line 1)

In [102]:
def mapping_function(value):
        if value == 0:
            return 'A'
        elif value == 25:
            return 'B'
        elif value == 50:
            return 'C'
        elif value == 75:
            return 'D'
        else:
            return 'E'
mapped_vals = map(mapping_function, f)
my_mapped_list = list(mapped_vals)

TypeError: 'numpy.ndarray' object is not callable