In [1]:
import numpy as np

In [2]:
print(np.version.version)

1.19.2


In [22]:
a = np.random.randint(0, 1000, [3, 2, 5])
print(a)

[[[175 526 579 326 271]
  [281 956 960 833 524]]

 [[770  36 595 563 544]
  [956 326 303 265 560]]

 [[860 985 138 101 189]
  [305  58 455 138  32]]]


In [23]:
b = np.ones([5, 2, 3])

In [15]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [17]:
a.shape == b.shape

False

In [24]:
c = a + b 

ValueError: operands could not be broadcast together with shapes (3,2,5) (5,2,3) 

In [25]:
c = np.transpose(b)

In [26]:
c.shape

(3, 2, 5)

In [28]:
d = c + a
print(d)

[[[176. 527. 580. 327. 272.]
  [282. 957. 961. 834. 525.]]

 [[771.  37. 596. 564. 545.]
  [957. 327. 304. 266. 561.]]

 [[861. 986. 139. 102. 190.]
  [306.  59. 456. 139.  33.]]]


In [29]:
print(a)
print(d)

[[[175 526 579 326 271]
  [281 956 960 833 524]]

 [[770  36 595 563 544]
  [956 326 303 265 560]]

 [[860 985 138 101 189]
  [305  58 455 138  32]]]
[[[176. 527. 580. 327. 272.]
  [282. 957. 961. 834. 525.]]

 [[771.  37. 596. 564. 545.]
  [957. 327. 304. 266. 561.]]

 [[861. 986. 139. 102. 190.]
  [306.  59. 456. 139.  33.]]]


In [30]:
e = a * c

In [31]:
e == a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [44]:
d_max = np.max(d)

d_min = np.min(d)
d_mean = np.mean(d)

In [45]:
f = np.empty([3, 2, 5])

In [56]:
p = list(d)
type(p)
print(p)

[array([[176., 527., 580., 327., 272.],
       [282., 957., 961., 834., 525.]]), array([[771.,  37., 596., 564., 545.],
       [957., 327., 304., 266., 561.]]), array([[861., 986., 139., 102., 190.],
       [306.,  59., 456., 139.,  33.]])]


In [65]:
def add_changes(array):
    for i in array:
        if i > d_min and i < d_mean:
            i = 25
        elif i > d_mean and i < d_max:
            i = 75
        elif i == d_mean:
            i = 50
        elif i == d_min:
            i = 0
        elif i == d_max:
            i = 100

In [67]:
add_changes(list(d))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()