# Supervised Learning Model Evaluation Lab

Complete the exercises below to solidify your knowledge and understanding of supervised learning model evaluation.

In [174]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
from sklearn.metrics import accuracy_score, balanced_accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier

## Regression Model Evaluation

In [2]:
from sklearn.datasets import load_boston

data = load_boston()

X = pd.DataFrame(data["data"], columns=data["feature_names"])
y = pd.DataFrame(data["target"], columns=['MEDV'])

data = pd.concat([X, y], axis=1)

## 1. Split this data set into training (80%) and testing (20%) sets.

The `MEDV` field represents the median value of owner-occupied homes (in $1000's) and is the target variable that we will want to predict.

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    test_size=0.20, 
                                                    random_state=123)

## 2. Train a `LinearRegression` model on this data set and generate predictions on both the training and the testing set.

In [10]:
lr = LinearRegression()

In [11]:
lr.fit(X_train, y_train)

LinearRegression()

In [12]:
y_pred = lr.predict(X_train)

In [15]:
y_pred_test = lr.predict(X_test)

## 3. Calculate and print R-squared for both the training and the testing set.

In [19]:
r2_score(y_train, y_pred)

0.7559380876016175

In [20]:
r2_score(y_test, y_pred_test)

0.6592466510354125

## 4. Calculate and print mean squared error for both the training and the testing set.

In [22]:
mean_squared_error(y_train, y_pred)

20.677107947815138

In [23]:
mean_squared_error(y_test, y_pred_test)

28.19248575846932

## 5. Calculate and print mean absolute error for both the training and the testing set.

In [25]:
mean_absolute_error(y_train, y_pred)

3.1749500258692462

In [26]:
mean_absolute_error(y_test, y_pred_test)

3.660152818697662

## Classification Model Evaluation

In [153]:
from sklearn.datasets import load_iris

data = load_iris()

X = pd.DataFrame(data["data"], columns=data["feature_names"])
y = pd.DataFrame(data["target"], columns=["class"])

data = pd.concat([X, y], axis=1)

In [171]:
data

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     class  
0        0  
1        0  
2        0  
3        0  
4        0  
..     ...  
145      2  
146      2  
147      2  
148      2  
149      2  

[150 rows x 5 columns]

## 6. Split this data set into training (80%) and testing (20%) sets.

The `class` field represents the type of flower and is the target variable that we will want to predict.

In [154]:
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    test_size=0.20,
                                                   random_state=78)

## 7. Train a `LogisticRegression` model on this data set and generate predictions on both the training and the testing set.

In [155]:
log = LogisticRegression(max_iter=10000)

In [156]:
log.fit(X_train, y_train.values.ravel())

LogisticRegression(max_iter=10000)

In [157]:
y_pred = log.predict(X_train)

In [158]:
y_pred_test = log.predict(X_test)

## 8. Calculate and print the accuracy score for both the training and the testing set.

In [159]:
accuracy_score(y_train, y_pred)

0.9916666666666667

In [160]:
accuracy_score(y_test, y_pred_test)

0.9333333333333333

## 9. Calculate and print the balanced accuracy score for both the training and the testing set.

In [161]:
balanced_accuracy_score(y_train, y_pred)

0.9904761904761905

In [162]:
balanced_accuracy_score(y_test, y_pred_test)

0.9555555555555556

## 10. Calculate and print the precision score for both the training and the testing set.

In [163]:
precision_score(y_train, y_pred, average=None)

array([1.        , 1.        , 0.97674419])

In [164]:
precision_score(y_test, y_pred_test, average=None)

array([1. , 1. , 0.8])

## 11. Calculate and print the recall score for both the training and the testing set.

In [165]:
recall_score(y_train, y_pred, average=None)

array([1.        , 0.97142857, 1.        ])

In [166]:
recall_score(y_test, y_pred_test, average=None)

array([1.        , 0.86666667, 1.        ])

## 12. Calculate and print the F1 score for both the training and the testing set.

In [167]:
f1_score(y_train, y_pred, average=None)

array([1.        , 0.98550725, 0.98823529])

In [168]:
f1_score(y_test, y_pred_test, average=None)

array([1.        , 0.92857143, 0.88888889])

## 13. Generate confusion matrices for both the training and the testing set.

In [169]:
confusion_matrix(y_train, y_pred)

array([[43,  0,  0],
       [ 0, 34,  1],
       [ 0,  0, 42]])

In [170]:
confusion_matrix(y_test, y_pred_test)

array([[ 7,  0,  0],
       [ 0, 13,  2],
       [ 0,  0,  8]])

## Bonus: For each of the data sets in this lab, try training with some of the other models you have learned about, recalculate the evaluation metrics, and compare to determine which models perform best on each data set.

In [181]:
model = RandomForestClassifier()
parameter_space = {'n_estimators': [100],
                   'max_features': ['sqrt'],
                   'max_depth' : [None],
                   'min_samples_leaf' : [1]
                  }
grid_search = GridSearchCV(model,
                           param_grid=parameter_space,
                           verbose=1,
                           n_jobs=-1,
                          cv=5)
grid_search.fit(X_train, y_train.values.ravel())

Fitting 5 folds for each of 1 candidates, totalling 5 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done   5 out of   5 | elapsed:    4.7s finished


GridSearchCV(cv=5, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'max_depth': [None], 'max_features': ['sqrt'],
                         'min_samples_leaf': [1], 'n_estimators': [100]},
             verbose=1)

In [185]:
grid_search.best_score_

0.9666666666666666

In [183]:
best_rf = grid_search.best_estimator_

In [184]:
best_rf.score(X_test, y_test)

0.9333333333333333

In [ ]:
# F1 0.92857143 y RF 0.9333333333333333
# Sorprendentemente muy parecidas, no sé por qué.