# Supervised Learning Model Evaluation Lab

Complete the exercises below to solidify your knowledge and understanding of supervised learning model evaluation.

In [89]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Lasso, Ridge, ElasticNet
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error, mean_squared_log_error
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, fbeta_score
from sklearn.metrics import confusion_matrix

## Regression Model Evaluation

In [42]:
from sklearn.datasets import load_boston

data = load_boston()

X = pd.DataFrame(data["data"], columns=data["feature_names"])
y = pd.DataFrame(data["target"], columns=['MEDV'])

data = pd.concat([X, y], axis=1)

## 1. Split this data set into training (80%) and testing (20%) sets.

The `MEDV` field represents the median value of owner-occupied homes (in $1000's) and is the target variable that we will want to predict.

In [152]:
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    test_size=0.2, 
                                                    random_state=78)

## 2. Train a `LinearRegression` model on this data set and generate predictions on both the training and the testing set.

In [153]:
#Training 
lr = LinearRegression()
lr.fit(X_train, y_train)
predictions_train = lr.predict(X_train)
predictions_test = lr.predict(X_test)

## 3. Calculate and print R-squared for both the training and the testing set.

In [154]:
print(lr.score(X_train, y_train)) #R squared for train
print(lr.score(X_test, y_test)) #R squared for test
lr.score(X, y) #R squared for the whole data set

0.9394429054589587
0.8739698090317127


0.929668997483073

In [155]:
#Another way of calculatingo the R2, the score has a R2 metric by default
r2_score(
    y_true=y_train,
    y_pred=lr.predict(X_train)
)

0.9394429054589587

## 4. Calculate and print mean squared error for both the training and the testing set.

In [156]:
mean_squared_error(
    y_true = y_train,
    y_pred=lr.predict(X_train)
)

0.04289040327945001

In [178]:
mean_squared_error(
    y_true = y_test,
    y_pred=lr.predict(X_test)
)

0.0628750619386233

## 5. Calculate and print mean absolute error for both the training and the testing set.

In [158]:
mean_absolute_error(
    y_true = y_train,
    y_pred=lr.predict(X_train)
)

0.1606928135468531

In [159]:
mean_absolute_error(
    y_true = y_test,
    y_pred=lr.predict(X_test)
)

0.19220784520508188

## Classification Model Evaluation

In [160]:
from sklearn.datasets import load_iris

data = load_iris()

X = pd.DataFrame(data["data"], columns=data["feature_names"])
y = pd.DataFrame(data["target"], columns=["class"])

data = pd.concat([X, y], axis=1)
data["class"].value_counts()
data.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'class'],
      dtype='object')

## 6. Split this data set into training (80%) and testing (20%) sets.

The `class` field represents the type of flower and is the target variable that we will want to predict.

In [161]:
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    test_size=0.2, 
                                                    random_state=78)

## 7. Train a `LogisticRegression` model on this data set and generate predictions on both the training and the testing set.

In [162]:
log = LogisticRegression(max_iter = 1000)
log.fit(X_train, y_train.values.ravel())
train_predictions = log.predict(X_train)
test_predictions = log.predict(X_test)
test_predictions

array([2, 2, 2, 1, 1, 1, 1, 0, 1, 2, 2, 2, 2, 0, 1, 1, 1, 1, 0, 0, 0, 2,
       2, 0, 1, 1, 1, 0, 1, 2])

## 8. Calculate and print the accuracy score for both the training and the testing set.

In [163]:
accuracy_score(
    y_true=y_train,
    y_pred=log.predict(X_train)
)

0.9916666666666667

In [164]:
log.score(X_train, y_train)

0.9916666666666667

In [165]:
accuracy_score(
    y_true=y_test,
    y_pred=log.predict(X_test)
)

0.9333333333333333

In [166]:
log.score(X_test, y_test)

0.9333333333333333

## 9. Calculate and print the balanced accuracy score for both the training and the testing set.

In [167]:
accuracy_score(
    y_true=y,
    y_pred=log.predict(X)
)

0.98

## 10. Calculate and print the precision score for both the training and the testing set.

In [168]:
precision_score(
    y_true=y_train,
    y_pred=log.predict(X_train),
    average = "weighted"
)

0.991860465116279

In [169]:
precision_score(
    y_true=y_test,
    y_pred=log.predict(X_test),
    average = "weighted"
)

0.9466666666666667

## 11. Calculate and print the recall score for both the training and the testing set.

In [170]:
recall_score(
    y_true=y_train,
    y_pred=log.predict(X_train),
    average = "weighted"
)

0.9916666666666667

In [171]:
recall_score(
    y_true=y_test,
    y_pred=log.predict(X_test),
    average = "weighted"
)

0.9333333333333333

## 12. Calculate and print the F1 score for both the training and the testing set.

In [172]:
f1_score(
    y_true=y_train,
    y_pred=log.predict(X_train),
    average = "weighted"
)

0.9916552998010798

In [173]:
f1_score(
    y_true=y_test,
    y_pred=log.predict(X_test),
    average = "weighted"
)

0.9346560846560847

## 13. Generate confusion matrices for both the training and the testing set.

In [176]:
confusion_matrix(
    y_true=y_train,
    y_pred=log.predict(X_train)
)

array([[43,  0,  0],
       [ 0, 34,  1],
       [ 0,  0, 42]])

In [177]:
confusion_matrix(
    y_true=y_test,
    y_pred=log.predict(X_test)
)

array([[ 7,  0,  0],
       [ 0, 13,  2],
       [ 0,  0,  8]])

## Bonus: For each of the data sets in this lab, try training with some of the other models you have learned about, recalculate the evaluation metrics, and compare to determine which models perform best on each data set.

#### KNN

Empezemos con un KNN classifier para el segundo ejemplo

In [186]:
from sklearn.model_selection import learning_curve, GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
import numpy as np

In [187]:
model = KNeighborsClassifier()
data = load_iris()
X = pd.DataFrame(data["data"], columns=data["feature_names"])
y = pd.DataFrame(data["target"], columns=["class"])

In [191]:
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y.values.ravel(), 
                                                    test_size=0.20, 
                                                    random_state=123)

Vamos a encontrar el modelo óptimo con un gridsearch

In [192]:
parameter_space = {'n_neighbors': np.arange(1,50),
                   }

grid_search = GridSearchCV(model,
                           param_grid=parameter_space,
                           cv=5)

grid_search.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])})

In [193]:
grid_search.best_estimator_

KNeighborsClassifier(n_neighbors=7)

In [194]:
grid_search.best_score_

0.975

Ganamos a el modelo de Logistic Regression, vamos a intentar mejorar aún más con una variable standarization

In [196]:
data = pd.concat([X, y], axis=1)
data

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     class  
0        0  
1        0  
2        0  
3        0  
4        0  
..     ...  
145      2  
146      2  
147      2  
148      2  
149      2  

[150 rows x 5 columns]

Nada todas las variables tienen la misma medida, cm. Por este motivo no tiene sentido hacer un estandarización de variables

#### RANDOM FOREST

In [197]:
from sklearn.ensemble import RandomForestClassifier

In [198]:
data = load_iris()

X = pd.DataFrame(data["data"], columns=data["feature_names"])
y = pd.DataFrame(data["target"], columns=["class"])

data = pd.concat([X, y], axis=1)

In [205]:
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y.values.ravel(), 
                                                    test_size=0.2, 
                                                    random_state=78)

In [208]:
model = RandomForestClassifier(n_estimators = 100,
                               random_state = 123,
                               max_features = "sqrt",
                               n_jobs = -1,
                               verbose = 1)
model.fit(X_train, y_train)

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:    0.1s
[Parallel(n_jobs=-1)]: Done 100 out of 100 | elapsed:    0.1s finished


RandomForestClassifier(max_features='sqrt', n_jobs=-1, random_state=123,
                       verbose=1)

In [210]:
model.score(X_test, y_test)

[Parallel(n_jobs=4)]: Using backend ThreadingBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:    0.0s
[Parallel(n_jobs=4)]: Done 100 out of 100 | elapsed:    0.0s finished


0.9333333333333333

No me acuerdo bien del código para encontrar el modelo óptimo, con el que seguro sube el score. 