In [12]:
#1. Import the NUMPY package under the name np.
import numpy as np

In [13]:
#2. Print the NUMPY version and the configuration.
print(np.version.version)

1.19.2


In [55]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

# FIRST WAY:
# Creamos una matriz tridimensional de numeros random del 0 al 1
a = np.random.random((2, 3, 5))
print(a)


[[[0.13781809 0.04904029 0.47748449 0.32123167 0.30030253]
  [0.377292   0.65492465 0.85686319 0.30380965 0.3375774 ]
  [0.42465742 0.87875356 0.15460259 0.44336082 0.28420633]]

 [[0.38902163 0.61721824 0.0498709  0.238995   0.14893881]
  [0.96522162 0.94641464 0.3240892  0.97532276 0.42411458]
  [0.01819332 0.91395787 0.30134794 0.72901263 0.0914358 ]]]


In [40]:
a.shape

(2, 3, 5)

In [56]:
# SECOND WAY
# Creamos una matriz tridimensional 
'''
a = np.random.randint(low = 10, high = 40, size = (2,3,5))

print(a)
'''

'\na = np.random.randint(low = 10, high = 40, size = (2,3,5))\n\nprint(a)\n'

In [57]:
# THIRD WAY
# Creamos una funcion tridimensional 
'''
a = np.random.randn(2,3,5)
print(a)
'''

'\na = np.random.randn(2,3,5)\nprint(a)\n'

In [ ]:
#4. print(a)

In [58]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

b = np.ones((5, 2, 3))
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [ ]:
#6. print(b)

In [62]:
#7. Do a and b have the same size? How do you prove that in Python code?
print(a.shape)
print(b.shape)

print(a.shape == b.shape)

(2, 3, 5)
(5, 2, 3)
False


In [41]:
a.shape

(2, 3, 5)

In [72]:
print(a.shape == b.shape)

False


In [95]:
print(a)

[[[0.13781809 0.04904029 0.47748449 0.32123167 0.30030253]
  [0.377292   0.65492465 0.85686319 0.30380965 0.3375774 ]
  [0.42465742 0.87875356 0.15460259 0.44336082 0.28420633]]

 [[0.38902163 0.61721824 0.0498709  0.238995   0.14893881]
  [0.96522162 0.94641464 0.3240892  0.97532276 0.42411458]
  [0.01819332 0.91395787 0.30134794 0.72901263 0.0914358 ]]]


In [96]:
a.shape

(2, 3, 5)

In [97]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [98]:
b.shape

(5, 2, 3)

In [106]:
# Transpone de b array to the same size of array a
c = b.reshape(2, 3, 5)
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [107]:
c.shape

(2, 3, 5)

In [108]:
a.shape == c.shape

True

In [111]:
d = a + c
print(d)

[[[1.13781809 1.04904029 1.47748449 1.32123167 1.30030253]
  [1.377292   1.65492465 1.85686319 1.30380965 1.3375774 ]
  [1.42465742 1.87875356 1.15460259 1.44336082 1.28420633]]

 [[1.38902163 1.61721824 1.0498709  1.238995   1.14893881]
  [1.96522162 1.94641464 1.3240892  1.97532276 1.42411458]
  [1.01819332 1.91395787 1.30134794 1.72901263 1.0914358 ]]]


In [115]:
print(a)

[[[0.13781809 0.04904029 0.47748449 0.32123167 0.30030253]
  [0.377292   0.65492465 0.85686319 0.30380965 0.3375774 ]
  [0.42465742 0.87875356 0.15460259 0.44336082 0.28420633]]

 [[0.38902163 0.61721824 0.0498709  0.238995   0.14893881]
  [0.96522162 0.94641464 0.3240892  0.97532276 0.42411458]
  [0.01819332 0.91395787 0.30134794 0.72901263 0.0914358 ]]]


In [114]:
e = a * c
print(e)

[[[0.13781809 0.04904029 0.47748449 0.32123167 0.30030253]
  [0.377292   0.65492465 0.85686319 0.30380965 0.3375774 ]
  [0.42465742 0.87875356 0.15460259 0.44336082 0.28420633]]

 [[0.38902163 0.61721824 0.0498709  0.238995   0.14893881]
  [0.96522162 0.94641464 0.3240892  0.97532276 0.42411458]
  [0.01819332 0.91395787 0.30134794 0.72901263 0.0914358 ]]]


In [116]:
a == e

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [118]:
print(d)

[[[1.13781809 1.04904029 1.47748449 1.32123167 1.30030253]
  [1.377292   1.65492465 1.85686319 1.30380965 1.3375774 ]
  [1.42465742 1.87875356 1.15460259 1.44336082 1.28420633]]

 [[1.38902163 1.61721824 1.0498709  1.238995   1.14893881]
  [1.96522162 1.94641464 1.3240892  1.97532276 1.42411458]
  [1.01819332 1.91395787 1.30134794 1.72901263 1.0914358 ]]]


In [119]:
np.amax(d)

1.9753227576307728

In [120]:
np.amin(d)

1.0181933187283698

In [121]:
np.mean(d)

1.4378359866012205

In [126]:
f = np.empty((2, 3, 5), dtype=int)

In [127]:
type(f)

numpy.ndarray