In [1]:
import numpy as np
print(np.version.version)

1.19.2


In [7]:
a = np.random.randn(2,3,5)
print(a)

[[[ 1.20329556 -1.58504109  0.49522842  0.11361188 -0.12975781]
  [ 2.34852397  0.82389647  1.9210007   0.16537059  0.31588747]
  [ 0.20910712  1.04308015  0.13170224  0.54508744 -1.42978433]]

 [[-1.67154664 -0.26528137  1.88530369  0.01469392  1.85388725]
  [ 0.80921894  1.3246805  -1.59226418  0.14796247  1.08010059]
  [ 0.06467678  1.37826999  0.68904387 -0.80963378  0.45541997]]]


In [8]:
np.random.randint(low=10, high=50, size=(2,3,5))

array([[[31, 36, 11, 23, 31],
        [34, 33, 22, 38, 38],
        [35, 27, 45, 44, 43]],

       [[19, 42, 28, 34, 31],
        [35, 20, 29, 13, 10],
        [47, 19, 31, 39, 12]]])

In [16]:
b = np.full((5,2,3), fill_value=1)
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [17]:
print(len(a))

2


In [18]:
print(len(b))

5


In [23]:
if len(a)==len(b):
    print (True)
else:
    print (False)

False
